apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: cert-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["issuers"]
  verbs: ["get", "watch", "list"]
