apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_int/sign/example-dot-com
    server: http://vault:8200
    auth:
      appRole:
        path: approle
        roleId: "665a3e04-d1db-851c-bb35-3aeb3046d11e"
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
